### ISSUE TITLE
Feature request: Task name

### ISSUE THREAD

**Issue by JumpLink** [elvishcraftsman/time-tracker#1]
Would be nice to be able to add a task name / description for a tracked task

**Comment by elvishcraftsman** [comment]
Thanks for the feature request. That's on the roadmap to happen before long.

Would you use it instead of the project name, or along with it?

**Comment by JumpLink** [comment]
Personally, I would need both. So far I have used Clockify, a proprietary online service, but I'm looking for a viable alternative that integrates well with the GNOME desktop and is adaptive, so also works well on a smartphone with Phosh or GNOME.

As a freelancer, I have several clients at the same time, so I need to be able to filter the times by project in order to write the invoice. I also need the title or description of the task for this to be able to tell customers what I have been working on and for how long. 

Are you aware that there are already several time trackers?

* https://gitlab.gnome.org/danigm/timetrack
* https://gitlab.com/idevecore/pomodoro
* https://gitlab.gnome.org/World/Solanum
* https://github.com/lakoliu/Furtherance
* And one of course


Currently Furtherance works best for me as a replacement for my previous time tracker, but I think yours is also very promising and since you developed it with GJS, I would most likely be able to contribute features to your app myself since I already have experience with GJS :)

**Comment by elvishcraftsman** [comment]
Ok, makes sense. I'll prioritize that feature. I also have a feature in the works for assigning projects or tasks to a client, so that they can be filtered by client as well as by projects.

I did check out the apps you mentioned before starting on Time Tracker, and Furtherance is definitely the closest to meeting my needs. However, since I use more than one computer, it was important for me to be able to sync between computers. I also wanted to build out more reporting features in time.

I'll definitely welcome code contributions. This is my first open source app project, so this is a new world for me. I feel like there's a niche Time Tracker can fill to replace Clockify and Toggl for Linux users, and I'd like to make sure I'm not the only person who's putting work into maintaining it.

**Comment by JumpLink** [comment]
That sounds great, the features you mentioned would also be important to me. Good luck, if I find the time I'll be happy to contribute, but at the moment it's not so easy with work and family.

**Comment by Scridgeon** [comment]
I'm currently using Clockify and moved to it from Furtherance because I need better reporting. Having both Project and Tag is incredibly important to align work. The # method of tagging in Furtherance is better than storing the value like Clockify does IMO.

**Comment by elvishcraftsman** [comment]
Okay, I'm testing out some preliminary support for task descriptions and tags. Seems to be working pretty well. I'll try to flesh it out over the next week and push out an update when it's stable.

**Comment by elvishcraftsman** [comment]
I pushed out an update with ability to add task descriptions, including tags and clients, as well as to filter by tags and clients (searching both description and project). Let me know how it's working, and if it fills the need you have.

**Comment by Scridgeon** [comment]
I like it! It's great to see the task along with the Project in the tracking section.

**Comment by tomaskikutis** [comment]
Since this is the first issue and already has some offtopic feedback, I'll add some more.

I was trying out various open source time trackers and this was one of the best UX wise.

One of the most lacking features for me is not being able to pause/resume tasks. I'll have to use Furtherance for the time being.

It would also be good to improve the UI of the list view. It feels cluttered now. If there's no project, I wouldn't output "Project: (no project)". I would take inspiration from Furtherance on list view UI - I think they nailed it. Maybe I'd improve time format to a more human readable form of `35m` vs `00:35:00`.

I would get rid of snackbars informing about file writes. It's not relevant to users unless there are errors.

The rest looks good. Best of luck with the project :rocket:

**Comment by elvishcraftsman** [comment]
@tomaskikutis Great to hear your feedback. Since I've closed this issue, I created a new one for this.
